meta_product_name: "NOORA"
meta_title: "NOORA - All you need as a freelancer, bookmarked."
meta_description: "NOORA is a one-stop-shop for freelancers. Find tools that make freelancing a breeze, pre- selected for you by other freelancers. Create your own toolbox, receive real-time updates from your favorite applications and make your very own collection public."
meta_image: "cover.png"
